name: 'Vaultwarden secrets replacement'
description: 'Get secrets from Vaultwarden and replaces them in the specified files'
inputs:
  BW_CLIENTID:
    description: 'VW OAuth client ID'
    required: true
    default: ''
  BW_CLIENTSECRET:
    description: 'VW OAuth client secret'
    required: true
    default: ''
  BW_PASSWORD:
    description: 'Password of your VW user'
    required: true
    default: ''
  BW_SERVER:
    description: 'Vaultwareden server'
    required: true
    default: ''
  FILES_TO_REPLACE:
    description: 'Files to process replacements'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.BW_CLIENTID }}
    - ${{ inputs.BW_CLIENTSECRET }}    
    - ${{ inputs.BW_PASSWORD }}
    - ${{ inputs.BW_SERVER }}
    - ${{ inputs.FILE_TO_REPLACE }}
